obj-$(CONFIG_SENSORS)		+= sensors_class.o
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
obj-$(CONFIG_SENSORS_CORE)      += sensors_core.o

# acclerometer_sensor
obj-$(CONFIG_SENSORS_K2HH)          += k2hh.o

# optical_sensor
obj-$(CONFIG_SENSORS_CM36655)	+= cm36655.o
obj-$(CONFIG_SENSORS_CM36686)	+= cm36686.o
obj-$(CONFIG_SENSORS_TMD3700)       += tmd37xx.o

# magnetic_sensor
obj-$(CONFIG_SENSORS_AK09911C)	+= ak09911c.o
obj-$(CONFIG_SENSORS_AK09916C)	+= ak09916c.o
